#!/usr/bin/env bash
apt-get -y update

pkgs=(amd64-microcode
aptitude
at
bash-completion
bc
beep
binwalk
ccrypt
clonezilla
coreutils
cpuid
curl
debsums
dislocker
dkms
dnsutils
dos2unix
dosfstools
dpkg
eject
ethtool
exfat-fuse
exfat-utils
fail2ban
figlet
flac
g++
gcc
gdisk
git
gpart
gparted
hashalot
hexedit
htop
hwinfo
iftop
intel-microcode
jq
libarchive-zip-perl
libnss-winbind
libsasl2-modules
links
locate
lshw
mailutils
make
mc
mlocate
mtr
ncurses-bin
net-tools
netcat
nmap
ntfs-3g
ntp
ntpdate
nvme-cli
openssh-server
openssl
p7zip-full
parallel
pciutils
perl
powertop
printer-driver-splix
procinfo
putty
pv
pwgen
python2
python3
rpm
rsync
samba
screen
scrub
secure-delete
shellcheck
smartmontools
smbclient
speedtest-cli
squashfs-tools-ng
ssh
sshfs
sshpass
strace
swaks
synaptic
sysvbanner
telnet
testdisk
tightvncserver
tmux
traceroute
tty-clock
udisks2
ufw
unrar
unzip
usbmount
util-linux
vsftpd
wget
winbind
zerofree
zip)

# apt-get purge -y cups

for p in ${pkgs[*]}
do
	apt-get -y install "$p"
done

apt-get clean
apt-get -y autoclean
apt-get -y autoremove

sync
