#!/usr/bin/env bash

swupd update

packets=(
	bc
	curl
	dev-utils
	dosfstools
	ethtool
	flac
	git
	gparted
	htop
	iftop
	jq
	make
	mtr
	net-tools
	nmap
	openssh-server
	openssl
	parallel
	powertop
	pwgen
	rsync
	samba
	smartmontools
	strace
	testdisk
	tmux
	unzip
	wget
	zip
)

for packet in ${packets[*]}
do
	swupd bundle-add "$packet"
done

sync
