#!/usr/bin/env bash
f="file.ext"
url="https://yourpage.com/"
cd || exit 1
rm -f $f
curl -o $f $url$f || wget --no-check-certificate $url$f || exit 1
rm -rf ./folder
7z x $f || exit 1
rm -f $f
chmod 700 folder/*
echo "done"
