#!/usr/bin/env bash
f="bench_result.txt"
if [[ "$1" =~ ^[0-9]+$ ]]; then
	{
		date "+%y%m%d"
		uname -a
		lsb_release -a
		apt-get update
		apt-get install p7zip-full stress-ng sysbench
		stress-ng --cpu "$1" --cpu-method matrixprod --metrics-brief -t 60
		sysbench --test=cpu --cpu-max-prime=20000 --num-threads="$1" --max-time=60 run
		7z b
	} | tee "$f"
	echo "Results are in file $f"
else
	echo "Please give number of threads on command line!"
fi
