#!/usr/bin/env bash

electrum daemon -d -D .

for file in *;
do
	echo Using wallet: $file
	electrum load_wallet -w "./$file" -D . --password xyz
	if [[ $? -ne 0 ]]; then
		#echo ERROR
		continue
	fi
	electrum unlock -w "./$file" -D . --password xyz
	electrum listaddresses -w "./$file" -D . | electrum getprivatekeys - -D . -w "./$file" | jq -r ".[]"
	electrum close_wallet -w "./$file" -D .
done 2> /dev/null

electrum stop
