#!/usr/bin/env bash
# Bash script to fetch currecy values from NBP site for PLN (Polish Złoty) for Dygraphs
# It is using background call so it is really fast ("multithreaded")
TMP1=$(curl --retry 5 -s -m 10 "http://www.nbp.pl/kursy/xml/dir.txt")
output="wal.csv"
echo "D,GBP,EUR,CHF,USD,NOK" > "$output"
while IFS= read -r p; do
	if [[ ${p:0:1} == "a" ]] ; then
	{
		sleep .$RANDOM
		a=$(echo -n "$p" | sed 's/\r//')
		TMP2=$(until curl --retry 5 -s -m 10 "http://www.nbp.pl/kursy/xml/$a.xml"; do :; done)
		while IFS= read -r q; do
			if [[ ${q:0:12} == "   <data_pub" ]] ; then
				d1="${q:20:10}"
			fi
			if [[ ${q:18:3} == "GBP" ]] ; then
				read -r q
				d2=$(echo -n "${q:13:6}" | sed 's/,/./')
				continue
			fi
			if [[ ${q:18:3} == "EUR" ]] ; then
				read -r q
				d3=$(echo -n "${q:13:6}" | sed 's/,/./')
				continue
			fi
			if [[ ${q:18:3} == "CHF" ]] ; then
				read -r q
				d4=$(echo -n "${q:13:6}" | sed 's/,/./')
				continue
			fi
			if [[ ${q:18:3} == "USD" ]] ; then
				read -r q
				d5=$(echo -n "${q:13:6}" | sed 's/,/./')
				continue
			fi
			if [[ ${q:18:3} == "NOK" ]] ; then
				read -r q
				d6=$(echo -n "${q:13:6}" | sed 's/,/./')
				continue
			fi
		done <<< "$TMP2"
		echo "$d1,$d2,$d3,$d4,$d5,$d6"
		>&2 echo -n .
	} &
	fi
done <<< "$TMP1" | sort >> "$output"
