#!/usr/bin/env bash
# apt install aria2
echo Downloading...
aria2c -x4 http://addresses.loyce.club/Bitcoin_addresses_LATEST.txt.gz
echo Unpacking...
pv Bitcoin_addresses_LATEST.txt.gz | gunzip > Bitcoin_addresses_LATEST.txt
echo Sorting...
pv -B 1M -cN input Bitcoin_addresses_LATEST.txt | cut -f 1 | LC_ALL=C sort -u -S 20% --parallel=16 | pv -cN output > addrs-with-bal.txt
echo Done!
>&2 echo -ne "\a"
