#!/usr/bin/env bash
i=0
mapfile -d '' files < <(find . -name "*.dat" -print0)
c=${#files[@]}
for f in "${files[@]}"; do
	a=$(./b2jshort02.py "$f")
	b=${a:12:64}
	if [ -z "$b" ]; then
		i=$((i+1))
		echo -ne "$i/$c\r"
		continue
	fi
	d=$(dirname "$f")
	nb="$d/$b"
	while [ -f "$nb.dat" ]
	do
		nb="${nb}_"
	done
	mv "$f" "$nb.dat"
	i=$((i+1))
	echo -ne "$i/$c\r"
done
echo
>&2 printf '\a'
